wandb_version: 1

_wandb:
  desc: null
  value:
    code_path: code/open_instruct/open_instruct/finetune_val.py
    python_version: 3.8.17
    cli_version: 0.15.10
    framework: huggingface
    huggingface_version: 4.31.0
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1699211242.060794
    t:
      1:
      - 1
      - 5
      - 11
      - 49
      - 51
      - 53
      - 55
      - 71
      - 98
      - 105
      3:
      - 13
      - 15
      - 23
      4: 3.8.17
      5: 0.15.10
      6: 4.31.0
      8:
      - 5
