wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.8.17
    cli_version: 0.15.10
    framework: huggingface
    huggingface_version: 4.31.0
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1706857804.430628
    t:
      1:
      - 1
      - 5
      - 11
      - 49
      - 51
      - 53
      - 55
      - 71
      - 98
      - 105
      2:
      - 1
      - 5
      - 11
      - 49
      - 51
      - 53
      - 55
      - 71
      - 98
      - 105
      3:
      - 13
      - 15
      - 23
      4: 3.8.17
      5: 0.15.10
      6: 4.31.0
      8:
      - 5
dataset_name:
  desc: null
  value: null
dataset_config_name:
  desc: null
  value: null
train_file:
  desc: null
  value: /home/caizf/projects/ZeroEE/data/mix_v2/GENEVA_n10_s2000_e96_6d_v2_GenData_e200_10d_5s_v2.json
val_file:
  desc: null
  value: /home/caizf/projects/ZeroEE/data/generated_data/valid_100_1definitions_v2.json
test_file:
  desc: null
  value: /home/caizf/projects/ZeroEE/data/ace_v2/ACE_test_v2_trigger.json
metrics_file:
  desc: null
  value: /home/caizf/projects/ZeroEE/ZeroEE/open_instruct/compute_score_ee.py
model_name_or_path:
  desc: null
  value: /home/models/Llama-2-7b-hf/
config_name:
  desc: null
  value: null
use_lora:
  desc: null
  value: false
lora_rank:
  desc: null
  value: 64
lora_alpha:
  desc: null
  value: 16
lora_dropout:
  desc: null
  value: 0.1
save_merged_lora_model:
  desc: null
  value: false
use_flash_attn:
  desc: null
  value: true
tokenizer_name:
  desc: null
  value: /home/models/Llama-2-7b-hf/
use_slow_tokenizer:
  desc: null
  value: true
max_seq_length:
  desc: null
  value: 256
per_device_train_batch_size:
  desc: null
  value: 8
per_device_eval_batch_size:
  desc: null
  value: 64
learning_rate:
  desc: null
  value: 2.0e-05
weight_decay:
  desc: null
  value: 0.0
num_train_epochs:
  desc: null
  value: 20
max_train_steps:
  desc: null
  value: 25540
gradient_accumulation_steps:
  desc: null
  value: 2
lr_scheduler_type:
  desc: null
  value: linear
warmup_ratio:
  desc: null
  value: 0.03
output_dir:
  desc: null
  value: output/GENEVA_n10_s2000_e96_6d_v2_GenData_e200_10d_5s_v2/
seed:
  desc: null
  value: null
preprocessing_num_workers:
  desc: null
  value: 16
overwrite_cache:
  desc: null
  value: false
checkpointing_steps:
  desc: null
  value: epoch
eval_steps:
  desc: null
  value: null
logging_steps:
  desc: null
  value: 1
resume_from_checkpoint:
  desc: null
  value: null
with_tracking:
  desc: null
  value: true
report_to:
  desc: null
  value: wandb
report_name:
  desc: null
  value: GENEVA_n10_s2000_e96_6d_v2_GenData_e200_10d_5s_v2/
report_tags:
  desc: null
  value:
  - ZeroEE
low_cpu_mem_usage:
  desc: null
  value: false
