wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.8.17
    cli_version: 0.15.8
    framework: huggingface
    huggingface_version: 4.31.0
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1699325114.66166
    t:
      1:
      - 1
      - 5
      - 11
      - 49
      - 51
      - 53
      - 55
      - 71
      - 98
      - 105
      2:
      - 1
      - 5
      - 11
      - 49
      - 51
      - 53
      - 55
      - 71
      - 98
      - 105
      3:
      - 13
      - 15
      - 23
      4: 3.8.17
      5: 0.15.8
      6: 4.31.0
      8:
      - 5
dataset_name:
  desc: null
  value: null
dataset_config_name:
  desc: null
  value: null
train_file:
  desc: null
  value: /local1/zefan/data/generated_data/train_1definitions_200.json
val_file:
  desc: null
  value: /local1/zefan/data/generated_data/val_1definitions.json
test_file:
  desc: null
  value: /local1/zefan/data/ace_v2/ACE_valid_GenerationStyle_trigger.json
model_name_or_path:
  desc: null
  value: /local1/zefan/models/Llama-2-7b-hf/
config_name:
  desc: null
  value: null
use_lora:
  desc: null
  value: false
lora_rank:
  desc: null
  value: 64
lora_alpha:
  desc: null
  value: 16
lora_dropout:
  desc: null
  value: 0.1
save_merged_lora_model:
  desc: null
  value: false
use_flash_attn:
  desc: null
  value: true
tokenizer_name:
  desc: null
  value: /local1/zefan/models/Llama-2-7b-hf/
use_slow_tokenizer:
  desc: null
  value: true
max_seq_length:
  desc: null
  value: 256
per_device_train_batch_size:
  desc: null
  value: 16
per_device_eval_batch_size:
  desc: null
  value: 256
learning_rate:
  desc: null
  value: 2.0e-05
weight_decay:
  desc: null
  value: 0.0
num_train_epochs:
  desc: null
  value: 20
max_train_steps:
  desc: null
  value: 31620
gradient_accumulation_steps:
  desc: null
  value: 1
lr_scheduler_type:
  desc: null
  value: linear
warmup_ratio:
  desc: null
  value: 0.03
output_dir:
  desc: null
  value: /local1/zefan/output/Llama2_Geneva_20_96_2000/
seed:
  desc: null
  value: null
preprocessing_num_workers:
  desc: null
  value: 16
overwrite_cache:
  desc: null
  value: false
checkpointing_steps:
  desc: null
  value: epoch
eval_steps:
  desc: null
  value: 4
logging_steps:
  desc: null
  value: 1
resume_from_checkpoint:
  desc: null
  value: /local1/zefan/ZeroEE/output/Llama-2-7b-geneva-20-96-2000/epoch_29
with_tracking:
  desc: null
  value: true
report_to:
  desc: null
  value: wandb
report_name:
  desc: null
  value: Llama2_Geneva_20_96_2000/
report_tags:
  desc: null
  value:
  - CtrlGen
low_cpu_mem_usage:
  desc: null
  value: false
