wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.8.17
    cli_version: 0.15.10
    framework: huggingface
    huggingface_version: 4.31.0
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1694443338.92937
    t:
      1:
      - 1
      - 11
      - 49
      - 51
      - 55
      - 71
      - 98
      - 105
      2:
      - 1
      - 11
      - 49
      - 51
      - 55
      - 71
      - 98
      - 105
      3:
      - 23
      4: 3.8.17
      5: 0.15.10
      6: 4.31.0
      8:
      - 5
dataset_name:
  desc: null
  value: null
dataset_config_name:
  desc: null
  value: null
train_file:
  desc: null
  value: /home/caizf/projects/ZeroEE/data_event_number/geneva/GENEVA_train_negatives15_samples20_events20.json
model_name_or_path:
  desc: null
  value: /home/models/Llama-2-7b-hf/
config_name:
  desc: null
  value: null
use_lora:
  desc: null
  value: false
lora_rank:
  desc: null
  value: 64
lora_alpha:
  desc: null
  value: 16
lora_dropout:
  desc: null
  value: 0.1
save_merged_lora_model:
  desc: null
  value: false
use_flash_attn:
  desc: null
  value: true
tokenizer_name:
  desc: null
  value: /home/models/Llama-2-7b-hf/
use_slow_tokenizer:
  desc: null
  value: true
max_seq_length:
  desc: null
  value: 256
per_device_train_batch_size:
  desc: null
  value: 8
learning_rate:
  desc: null
  value: 2.0e-05
weight_decay:
  desc: null
  value: 0.0
num_train_epochs:
  desc: null
  value: 30
max_train_steps:
  desc: null
  value: 4890
gradient_accumulation_steps:
  desc: null
  value: 1
lr_scheduler_type:
  desc: null
  value: linear
warmup_ratio:
  desc: null
  value: 0.03
output_dir:
  desc: null
  value: /home/caizf/ZeroEE/output/Llama-2-7b-geneva-15-20-20/
seed:
  desc: null
  value: null
preprocessing_num_workers:
  desc: null
  value: 16
overwrite_cache:
  desc: null
  value: false
checkpointing_steps:
  desc: null
  value: epoch
save_epochs:
  desc: null
  value: 1
logging_steps:
  desc: null
  value: 1
resume_from_checkpoint:
  desc: null
  value: null
with_tracking:
  desc: null
  value: true
report_to:
  desc: null
  value: wandb
low_cpu_mem_usage:
  desc: null
  value: false
